server:
  port: 8761
spring:
  application:
    name: registry-service
eureka:
  instance:
    hostname: ps-service-registry-production.up.railway.app
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      default-zone: https://${eureka.instance.hostname}:${server.port}/eureka/
